#!/usr/bin/env python
#
# Repetition trainer. Some things need to be rote-learned and doing so is
# easiest by repetition. This tool simply prints an item from a source file on
# the shell. Hook this up to frequently used commands and you're constantly
# exposed to the what you want to rote-learn.
#
# For example, I use it to teach myself vocabulary in various languages
#
# invocation:
#   $> shelltrainer --add-to spanish azul blue
#
#   $> shelltrainer [category]
#   [spanish] azul: blue
#
# The category matches the name of a .json file in $HOME/.shelltrainer. If
# none is given, a random one is picked. The category is only displayed if
# none is given.
#
# Example hook:
#    alias mutt="mutt; shelltrainer"
# i.e. whenever I quit mutt, I see one word displayed
#
# Config file format:
# {
# "words" : [
#     { 
#        "definition" : "zapato",
#        "description" : "shoe"
#    },
#    { 
#        "definition" : "azul",
#        "description" : "blue"
#    }
#]
#}

import json
import sys
import os
import random
import argparse

config="~/.shelltrainer"

class ShellTrainerCLI:
    def __init__(self):
        self.parser = argparse.ArgumentParser()
        self.parser.add_argument('--add-to')
        self.parser.add_argument('args', nargs="*")

    def parse_args(self, argv):
        args = self.parser.parse_args(argv)
        category = args.add_to
        st = ShellTrainer()
        if category != None:
            st.add(category, *args.args)
        else:
            st.pick_one(args.args[0] if len(args.args) > 0 else None)


class ShellTrainer(object):
    config_path = os.path.expanduser(config)

    def __init__(self):
        self.categories = {}
        self.load_source(self.config_path)

    def load_source(self, path):
        if not os.path.isdir(path):
            os.mkdir(path)
        for f in os.listdir(path):
            if not f.endswith(".json"):
                continue

            category = f[:f.rfind(".json")]

            with open(os.path.join(path, f)) as fp:
                j = json.load(fp)
                self.categories[category] = j


    def pick_one(self, category = None):
        if category == None:
            category = random.sample(self.categories.keys(), 1)[0]
            print "[%s]" % category,

        entry = random.sample(self.categories[category]["words"], 1)[0]
        print "%s: %s" % (entry["definition"], entry["description"])

    def add(self, category, definition, description):
        j = self.categories[category]
        j['words'].append({u'definition':definition, u'description':description})

        fname = category + ".json"
        with open(os.path.join(self.config_path, fname), "w") as fp:
            json.dump(j, fp, indent=4)

if __name__ == "__main__":
    cli = ShellTrainerCLI()
    cli.parse_args(sys.argv[1:])

