#!/usr/bin/env python
#
# Repetition trainer. Displays an item from a source file on the shell. Hook
# this up to frequently used commands and you're constantly exposed to the
# what you want to rote-learn
#
# invocation:
#   shelltrainer [category]
#
# Where category matches the name of a .json file in $HOME/.shelltrainer. If
# none is given, a random one is picked.
#
# Example hook:
#    alias mutt="mutt; shelltrainer"
#
# Config file format:
# {
# "words" : [
#     { 
#        "word" : "zapato",
#        "translation" : "shoe"
#    },
#    { 
#        "word" : "azul",
#        "translation" : "blue"
#    }
#]
#}

import json
import sys
import os
import random
import argparse

config="~/.shelltrainer"

class ShellTrainerCLI:
    def __init__(self):
        self.parser = argparse.ArgumentParser()
        self.parser.add_argument('--add-to')
        self.parser.add_argument('args', nargs="*")

    def parse_args(self, argv):
        args = self.parser.parse_args(argv)
        category = args.add_to
        st = ShellTrainer()
        if category != None:
            st.add(category, *args.args)
        else:
            st.pick_one(args.args[0] if len(args.args) > 0 else None)


class ShellTrainer(object):
    config_path = os.path.expanduser(config)

    def __init__(self):
        self.categories = {}
        self.load_source(self.config_path)

    def load_source(self, path):
        if not os.path.isdir(path):
            os.mkdir(path)
        for f in os.listdir(path):
            if not f.endswith(".json"):
                continue

            category = f[:f.rfind(".json")]

            with open(os.path.join(path, f)) as fp:
                j = json.load(fp)
                self.categories[category] = j


    def pick_one(self, category = None):
        if category == None:
            category = random.sample(self.categories.keys(), 1)[0]

        entry = random.sample(self.categories[category]["words"], 1)[0]
        print "%s: %s" % (entry["word"], entry["translation"])

    def add(self, category, word, translation):
        j = self.categories[category]
        j['words'].append({u'word':word, u'translation':translation})

        fname = category + ".json"
        with open(os.path.join(self.config_path, fname), "w") as fp:
            json.dump(j, fp, indent=4)

if __name__ == "__main__":
    cli = ShellTrainerCLI()
    cli.parse_args(sys.argv[1:])

